### ISSUE TITLE
issue with adding new Keyword.

### ISSUE THREAD

**Issue by shan1982** [fge/json-schema-validator#129]
Hi..this is shan, i came across this project, it's really nice. I am trying to add custom keyword to validate fields value based on reference data(from DB). 

I have implemented someway by using the sample implementation for 'divisors'. When i try with simple JSON, it's working well, but when i try with complex one, it's not getting validated. 

I am using V2.2.6 and having few questions: I build as 

final Keyword keyword = Keyword.newBuilder("reference")
	            .withSyntaxChecker(ReferenceSyntaxChecker.getInstance())
	            .withDigester(ReferenceDigesters.getInstance())
	            .withValidatorClass(ReferenceValidator.class)
	            .freeze();
		
		
		final Library library = DraftV4Library.get().thaw()
	            .addKeyword(keyword).freeze();
		
        
        final ValidationConfiguration cfg = ValidationConfiguration.newBuilder()
                .setDefaultLibrary("http://sample/draft-01/schema#", library)
                .freeze();

        final JsonSchemaFactory factory = JsonSchemaFactory.newBuilder()
                .setValidationConfiguration(cfg).freeze();

and use 'http://sample/draft-01/schema#' for $schema in schema file

But it's not even hitting ReferenceValidator contractor/validate method. As i mentioned when i try json and schema with only the created custom key, it's working and getting validated properly. For Example:
 
In Json
gender : "2"

In Json schema
{
    "type":"object",
	"properties":{
		"gender":{
		        "type": "string",
		        "reference": "/gender-id"
		}
	}
}

But try with complex structure, not getting validated. Can you please advice me on this???

**Comment by santoshgangavaram** [comment]
@shan1982 did you get above crossFields example working for you? I am facing same problem now. let me know if you figured out the root cause and the fix for it. thanks.
