### ISSUE TITLE
Not supporting Boolean type keyword.

### ISSUE THREAD

**Issue by shan1982** [fge/json-schema-validator#137]
Hi Francis,

I am try to create a keyword (boolean). My implementation looks like: 

      public static final class UniqueValueDigesters extends AbstractDigester {
		private static final Digester INSTANCE = new UniqueValueDigesters();

		public static Digester getInstance() {
			return INSTANCE;
		}

		private UniqueValueDigesters() {
                 //       super("uniqueValue", NodeType.OBJECT);
                //       super("uniqueValue", NodeType.STRING);
			super("uniqueValue", NodeType.BOOLEAN);
		}

		@Override
		public JsonNode digest(final JsonNode schema) {
			final ObjectNode ret = FACTORY.objectNode();
			ret.put(keyword, schema.get(keyword).asBoolean());
	        return ret;
		}

	}

	public static final class UniqueValueSyntaxChecker extends
			AbstractSyntaxChecker {
		private static final SyntaxChecker INSTANCE = new UniqueValueSyntaxChecker();

		public static SyntaxChecker getInstance() {
			return INSTANCE;
		}

		private UniqueValueSyntaxChecker() {
                  //       super("uniqueValue", NodeType.STRING);
			super("uniqueValue", NodeType.BOOLEAN);
		}

		@Override
		protected void checkValue(
				Collection<com.github.fge.jackson.jsonpointer.JsonPointer> pointers,
				MessageBundle bundle, ProcessingReport report, SchemaTree tree)
				throws ProcessingException {

		}
	}

        public static final class UniqueValueValidator extends
			AbstractKeywordValidator {
		
		private final boolean isUnique;
		public UniqueValueValidator(final JsonNode digest) {
			super("uniqueValue");
			isUnique = digest.get("uniqueValue").asBoolean();
		}

		@Override
		public void validate(final Processor<FullData, FullData> processor,
				final ProcessingReport report, final MessageBundle bundle,
				final FullData data) throws ProcessingException {

                }
		
		
		@Override
		public String toString() {
			return "uniqueValue";
		}

	}

when i try with the keyword type as ' NodeType.BOOLEAN', it never enter into validate method to validate, but when i try with NodeType.STRING, hit the validation part... Can you please advice me on this? I want my schema to hold as "uniqueValue" : true instead "uniqueValue" : "true"

**Comment by fge** [comment]
Can you please tell me what this keyword is supposed to do?

**Comment by shan1982** [comment]
This issue has been resolved.
