### ISSUE TITLE
How many layers of $ref the validator can do?

### ISSUE THREAD

**Issue by weiqitoby** [fge/json-schema-validator#141]
Hey fge,

Thank you very much first for this wonderful repo and api you worked out. 

I am currently doing json validation as a part of a project in which I have a problem regarding to "$ref". I tried the fstab-good.json against /split/fstab.json and /split/mntent.json. It works well enough! But in my case, the schema is a little bit more complicated. Reference exists in multiple layers from top level schema to bottom level schema. For example, I have an a.json in which there is a $ref references a b.json, a $ref reference d.json. And in b.json, there is a $ref references a c.json. This is just an example. Actually, the whole schema is like a tree with multiple layers. I tried that in the validator, it failed all the time. My question is, does the validator take care of this situation? Thanks!

Toby

Graph of the schema
                             a.json
                              /     \       ......
                        b.json  d.json
                         /         ......
                      c.json    ......

**Comment by fge** [comment]
Hello, and thank you for you appreciation!

Any number of "levels" are supported; JSON references are just solved as they are encountered and their results cached.

You said that it failed "at the time"; when was it, and what was the error?

**Comment by weiqitoby** [comment]
Hey fge,

Thank you for your response. After several times of debugging, I found the problem was from JSON schema developer side...It finally worked!

Thank you very much!
Toby
