### ISSUE TITLE
String type minLenght and maxLenght validation cause exeption

### ISSUE THREAD

**Issue by denissroos** [fge/json-schema-validator#154]
Hi,
I'm  trying validate json input. I'm loading json schema from string and using draft 4 version.
I got level "fatal" exeption. In shema is used string type min and maxLenght parameteres validation. Validate method wait for ingeger, but got number and causes exeption.

What am I doing wrong?

**Comment by fge** [comment]
And what is the error message?

**Comment by denissroos** [comment]
ERROR biombuffer.ValidationService  - com.github.fge.jsonschema.core.exceptions.InvalidSchemaException: fatal: invalid JSON Schema, cannot continue
Syntax errors:
 ...
"keyword" : "maxLength",
  "found" : "number",
  "expected" : [ "integer" ]
 ...

But when i trying validate this json against schema using online-validator http://json-schema-validator.herokuapp.com/, result is success

And when i delete man and minLehght params from the schema, validation result in my app also is ok.

**Comment by fge** [comment]
The validator can't lie, the schema is not the same ;)

Do verify the value of member `maxLength` in your schema when your input is a string; the problem is definitely there. Also, how do you load it etc.

**Comment by denissroos** [comment]
In store schemas in postgreSQL as json type and  load schema from database as JSON object. Then i use toString() method for converting this into a string and put jsonData and jsonSchema in validate method. My validation method is below

boolean validate(String jsonData, String jsonSchema){
		
		JsonNode schemaNode = JsonLoader.fromString(jsonSchema)
		JsonSchemaFactory factory = JsonSchemaFactory.byDefault()
		JsonSchema schema = factory.getJsonSchema(schemaNode)
		JsonNode data = JsonLoader.fromString(jsonData)
		try{
			return schema.validate(data).isSuccess()
		}
		catch(InvalidSchemaException e){
			log.error e
			return false
		}
}

**Comment by fge** [comment]
This still doesn't tell what the string actually contains, and this is your problem here.

Also, you are wasting resources; a JsonSchemaFactory is thread safe and immutable, therefore you had better use one for all your validations rather than initialize one each and every time!

**Comment by denissroos** [comment]
Thank you for help. I decided to load json from DB string type  and doesn't make schema convertation into JSON object. Now it work, minLength and maxLength params are integer
