### ISSUE TITLE
Validate does not report fields not documented in schema

### ISSUE THREAD

**Issue by sdetweil** [fge/json-schema-validator#162]
if we have a structure with 3 fields, 1 of which is required, and the 1 field is supplied, all is good.

however, if the incoming request data has a field which is NOT listed in the schema, validation is still successful..

if the schema says name, address, city(required)
and the data has city, foobar, it still passes validation.  with no warnings for the unexpected data element.  is there any way to turn on this kind of validation?

**Comment by box-jhuffaker** [comment]
I believe by default the object is "open".  To make it closed and reject these objects use:
  "additionalProperties": false

See:
http://json-schema.org/example2.html

**Comment by sdetweil** [comment]
Thank.. this works great..   

followup, our process today takes the swagger yaml, and converts to json for validation. (as the spec is changing daily).   the converter is small python script the reads the yaml, then  uses json class dump() to express the yaml object in json,

I haven't found a way to express the additionalProperties tag in yaml, such that it would flow thru the converter. 

converter tojosn.py 

import sys, yaml, json;
with open(sys.argv[1], 'r') as f:
    doc = yaml.load(f);
json.dump(doc, sys.stdout, indent=4);
